# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qr_solve <- function(A, b) {
    .Call('_hiperGLM_qr_solve', PACKAGE = 'hiperGLM', A, b)
}

